/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class petric_bogdan_onlineshop_JNIexample */

#ifndef _Included_petric_bogdan_onlineshop_JNIexample
#define _Included_petric_bogdan_onlineshop_JNIexample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     petric_bogdan_onlineshop_JNIexample
 * Method:    smanjiCenu
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_petric_bogdan_onlineshop_JNIexample_smanjiCenu
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
